CREATE TABLE IF NOT EXISTS orders (
    id INT AUTO_INCREMENT PRIMARY KEY,
	productName VARCHAR(100) NOT NULL,
    price MEDIUMINT UNSIGNED NOT NULL,
    total MEDIUMINT UNSIGNED NOT NULL,
    quantity MEDIUMINT DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET = latin1
