CREATE TABLE IF NOT EXISTS products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    slug varchar(100) UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    price MEDIUMINT NOT NULL,
    description TEXT,
    quantity MEDIUMINT DEFAULT 0,
    image VARCHAR(500)
) ENGINE = InnoDB DEFAULT CHARSET = latin1